service: osm-mapimage2

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-1
  cfLogs: true
  profile: personal-dev

functions:
  map:
    handler: handler.map
    events:
      - http:
          path: map
          method: get
          cors: true
